"""Add job enrichment fields

Revision ID: 84c1026537da
Revises: 559a83b10c7a
Create Date: 2026-07-25 22:07:24.511434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c1026537da'
down_revision: Union[str, Sequence[str], None] = '559a83b10c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_family', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('enrichment_version', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('enriched_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_jobs_job_family'), 'jobs', ['job_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_family'), table_name='jobs')
    op.drop_column('jobs', 'enriched_at')
    op.drop_column('jobs', 'enrichment_version')
    op.drop_column('jobs', 'job_family')
    # ### end Alembic commands ###
